version: '3.4'

services:
  app:
    image: ${DOCKER_REGISTRY-}dev-app
    build:
      context: ./app
      dockerfile: .Dockerfile
      target: develop-stage
    ports:
      - "9102:9102"
    command: /bin/sh -c "yarn && quasar dev -m ssr"
