version: '3.4'

services:
  app:
    build:
      context: ./app
      dockerfile: .Dockerfile
      target: production-stage
    volumes:
      - app:/app
    ports:
      - "3000:3000"
  
volumes:
  app: